[package]
name = "backend"
version = "0.1.0"
authors = ["happysalada <raphael@megzari.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trillium = "0.1.3"
trillium-smol = "0.1.2"
